### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by darkleaf** [darkleaf/web-template#1]
По аналогии с https://github.com/darkleaf/di/blob/master/.github/workflows/test.yml настроить CI.

Там какой-то странный ключ `restore-keys: test-`. Может быть там ошибка. Если это так, то еще исправить в di.

**Comment by amiskov** [comment]
> Там какой-то странный ключ restore-keys: test-. Может быть там ошибка. Если это так, то еще исправить в di.

Ошибки нет. Если не найдётся кэш с ключом `test-${{ hashFiles('deps.edn') }}`, то будет искаться кэш с ключом `test-<anything>`. Если таких найдётся несколько, то [будет использован](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-multiple-restore-keys) тот, у которого самая поздняя дата создания.
