### ISSUE TITLE
Строки как теги

### ISSUE THREAD

**Issue by darkleaf** [darkleaf/web-template#5]
Сейчас теги задаются или символами или кейвордами.
Нужно, чтобы было еще задавались строками.

```clj
["div" ..]
["ns:foo" ..]
```

там внутри все должно быть готово, нужно
1) написать тест по аналогии с кейвордами и символами, в core_test.clj
2) исправить условие

```clj
(defn- vector-tag-element [[tag :as node]]
  (when (ident? tag) ;; todo? string
```
сделать функцию tag? которая или ident? или string?

**Comment by amiskov** [comment]
> сделать функцию tag? которая или ident? или string?

Там получается чуть сложнее. `parse-tag` добавляет неймспейсы и если строку оставить строкой, то будет ошибка:

https://github.com/darkleaf/web-template/blob/1ff4ccdd45694c4ec4515f897fe64b1406d4efa6/src/darkleaf/web_template/internal/tag.clj#L17-L18

Я добавил нормализацию, чтоб тэги соответствовали `ident?` и `(namespace s)` не возвращала ошибок.

**Comment by darkleaf** [comment]
https://github.com/darkleaf/web-template/commit/9ffc13f9fd109f302b1120bc8d0de6d9f5f8728e
